hair_colors = [
    "aqua hair",
    "black hair",
    "blonde hair",
    "blue hair",
    "light blue hair",
    "dark blue hair",
    "brown hair",
    "light brown hair",
    "green hair",
    "dark green hair",
    "light green hair",
    "grey hair",
    "orange hair",
    "pink hair",
    "purple hair",
    "light purple hair",
    "red hair",
    "white hair",
]

eye_colors = [
    "aqua eyes",
    "black eyes",
    "blue eyes",
    "brown eyes",
    "green eyes",
    "grey eyes",
    "orange eyes",
    "purple eyes",
    "pink eyes",
    "red eyes",
    "white eyes",
    "yellow eyes",
    "amber eyes",
]