hair_style = [
    "bob cut",
    "pixie cut",
    "hime cut",
    "braid",
    "braided ponytail",
    "crown braid",
    "side braid",
    "single braid",
    "multiple braids",
    "twin braids",
    "french braid",
    "one side up",
    "two side up",
    "twintails",
    "low twintails",
    "short twintails",
    "ponytail",
    "single side bun",
    "hair bun",
    "braided bun",
    "wavy hair",
    "single hair bun",
    "double bun",
    "folded ponytail",
    "front ponytail",
    "high ponytail",
    "short ponytail",
    "side ponytail",
    "split ponytail",
    "blunt bangs",
    "hair over eyes",
    "hair over one eye",
    "crossed bangs",
    "hair between eyes",
    "parted bangs",
    "braided bangs",
    "arched bangs",
    "diagonal bangs",
    "swept bangs",
    "sidelocks",
    "ahoge",
    "heart ahoge",
    "huge ahoge",
    "antenna hair",
]