save_tags = [
    "1girl",
    "2girls",
    "3girls",
    "4girls",
    "5girls",
    "6+girls",
    "1boy",
    "2boys",
    "3boys",
    "4boys",
    "5boys",
    "6+boys",
    "solo",
    "indoors",
    "outdoors",
    "simple background",
    "standing",
    "from side",
    "scenery",
    "closed eyes",
    "animal",
    "sky",
    "city",
    "no humans",
]