tag_config_data = {
    "ahoge": ['antenna hair', 'huge ahoge', 'heart ahoge'],
    "animal ears": ['fake animal ears', 'horse ears', 'cat ears', 'dog ears', 'rabbit ears', 'fox ears', 'wolf ears', 'tiger ears', 'cow ears', 'mouse ears', 'bear ears', 'lion ears', 'floppy ears', 'raccoon ears', 'monkey ears', 'animal ear fluff', 'animal ear headphones'],
    "apron": ['aqua apron', 'black apron', 'blue apron', 'brown apron', 'green apron', 'grey apron', 'orange apron', 'pink apron', 'purple apron', 'red apron', 'sepia apron', 'white apron', 'yellow apron'],
    "argyle": ['argyle legwear'],
    "armor": ['japanese armor', 'aqua armor', 'black armor', 'blue armor', 'brown armor', 'green armor', 'grey armor', 'orange armor', 'pink armor', 'purple armor', 'red armor', 'sepia armor', 'white armor', 'yellow armor', 'shoulder armor', 'bikini armor', 'power armor'],
    "ascot": ['aqua ascot', 'black ascot', 'blue ascot', 'brown ascot', 'green ascot', 'grey ascot', 'orange ascot', 'pink ascot', 'purple ascot', 'red ascot', 'sepia ascot', 'white ascot', 'yellow ascot', 'frilled ascot'],
    "ass": ['ass grab'],
    "axe": ['battle axe'],
    "bag": ['shoulder bag', 'handbag', 'school bag', 'shopping bag', 'paper bag', 'aqua bag', 'black bag', 'blue bag', 'brown bag', 'green bag', 'grey bag', 'orange bag', 'pink bag', 'purple bag', 'red bag', 'sepia bag', 'white bag', 'yellow bag', 'animal bag'],
    "ball": ['baseball'],
    "balloon": ['holding balloon'],
    "bandages": ['bandaged leg', 'bandaged arm'],
    "bandaid": ['bandaid on face', 'bandaid on hand', 'bandaid on leg', 'bandaid on nose', 'bandaid on knee', 'bandaid on nipples', 'bandaid on cheek', 'bandaid on pussy', 'bandaid on arm', 'bandaid on hand'],
    "bandana": ['aqua bandana', 'black bandana', 'blue bandana', 'brown bandana', 'green bandana', 'grey bandana', 'orange bandana', 'pink bandana', 'purple bandana', 'red bandana', 'sepia bandana', 'white bandana', 'yellow bandana'],
    "bangs": ['blunt bangs', 'dyed bangs', 'swept bangs', 'parted bangs', 'asymmetrical bangs', 'crossed bangs', 'long bangs', 'hair over eyes', 'hair over one eye', 'hair between eyes', 'bangs pinned back'],
    "bed": ['bed sheet', 'on bed'],
    "bell": ['neck bell', 'cowbell'],
    "bikini": ['aqua bikini', 'black bikini', 'blue bikini', 'brown bikini', 'green bikini', 'grey bikini', 'orange bikini', 'pink bikini', 'purple bikini', 'red bikini', 'sepia bikini', 'white bikini', 'yellow bikini', 'micro bikini', 'striped bikini'],
    "boots": ['armored boots', 'ballet boots', 'belt boots', 'combat boots', 'cowboy boots', 'frilled boots', 'fur-trimmed boots', 'high heel boots', 'lace-up boots', 'platform boots', 'santa boots', 'snow boots', 'spiked boots', 'toeless footwear', 'Ugg boots', 'riding boots', 'fur boots', 'latex boots', 'leather boots', 'metal boots', 'rubber boots', 'ankle boots', 'knee boots', 'thigh boots', 'boots removed', 'putting on boots', 'single boot', 'single thigh boot', 'single knee boot', 'thighhighs under boots', 'torn boots'],
    "bow": ['hair bow', 'print bow', 'bowtie', 'aqua bow', 'black bow', 'blue bow', 'brown bow', 'green bow', 'grey bow', 'orange bow', 'pink bow', 'purple bow', 'red bow', 'sepia bow', 'white bow', 'yellow bow'],
    "bowtie": ['aqua bowtie', 'black bowtie', 'blue bowtie', 'brown bowtie', 'green bowtie', 'grey bowtie', 'orange bowtie', 'pink bowtie', 'purple bowtie', 'red bowtie', 'sepia bowtie', 'white bowtie', 'yellow bowtie'],
    "braid": ['twin braids', 'single braid', 'french braid', 'crown braid', 'side braid', 'side braids', 'braided bangs', 'long braid', 'low twin braids', 'multiple braids'],
    "breasts": ['small breasts', 'medium breasts', 'large breasts', 'huge breasts', 'gigantic breasts', 'asymmetrical breasts', 'perky breasts', 'pointy breasts', 'sagging breasts', 'breasts apart', 'breasts out', 'bouncing breasts', 'hanging breasts', 'breasts squeezed together', 'covering breasts'],
    "brooch": ['heart brooch'],
    "candy": ['holding candy'],
    "cardigan": ['aqua cardigan', 'black cardigan', 'blue cardigan', 'brown cardigan', 'green cardigan', 'grey cardigan', 'orange cardigan', 'pink cardigan', 'purple cardigan', 'red cardigan', 'sepia cardigan', 'white cardigan', 'yellow cardigan'],
    "cellphone": ['smartphone'],
    "chair": ['office chair'],
    "child": ['female child'],
    "choker": ['aqua choker', 'black choker', 'blue choker', 'brown choker', 'green choker', 'grey choker', 'orange choker', 'pink choker', 'purple choker', 'red choker', 'sepia choker', 'white choker', 'yellow choker', 'frilled choker', 'ribbon choker'],
    "clothes lift": ['shirt lift', 'skirt lift', 'dress lift', 'bra lift', 'sweater lift', 'bikini top lift'],
    "clothing cutout": ['cleavage cutout', 'navel cutout'],
    "coat": ['duffel coat', 'fur coat', 'fur-trimmed coat', 'long coat', 'overcoat', 'peacoat', 'trench coat', 'winter coat', 'open coat', 'naked coat', 'labcoat', 'aqua coat', 'black coat', 'blue coat', 'brown coat', 'green coat', 'grey coat', 'orange coat', 'pink coat', 'purple coat', 'red coat', 'sepia coat', 'white coat', 'yellow coat'],
    "collar": ['sailor collar'],
    "cowgirl position": ['squatting cowgirl position', 'reverse cowgirl position'],
    "cum": ['cum in pussy', 'cum on body'],
    "dark skin": ['dark-skinned female'],
    "denim": ['denim skirt', 'denim shorts', 'denim jacket'],
    "dress": ['aqua dress', 'black dress', 'blue dress', 'brown dress', 'green dress', 'grey dress', 'orange dress', 'pink dress', 'purple dress', 'red dress', 'sepia dress', 'white dress', 'yellow dress'],
    "earrings": ['hoop earrings', 'cross earrings', 'star earrings', 'stud earrings', 'tassel earrings', 'crescent earrings', 'flower earrings', 'feather earrings', 'skull earrings', 'ear piercing'],
    "fang": ['skin fang'],
    "fat": ['fat man'],
    "fellatio": ['blowjob'],
    "fingerless gloves": ['partially fingerless gloves'],
    "fishing rod": ['holding fishing rod'],
    "fishnets": ['fishnet pantyhose', 'fishnet thighhighs', 'fishnet legwear', 'fishnet top', 'fishnet gloves'],
    "flower": ['aqua flower', 'black flower', 'blue flower', 'brown flower', 'green flower', 'grey flower', 'orange flower', 'pink flower', 'purple flower', 'red flower', 'sepia flower', 'white flower', 'yellow flower'],
    "food": ['holding food'],
    "glasses": ['aqua-framed eyewear', 'black-framed eyewear', 'blue-framed eyewear', 'brown-framed eyewear', 'green-framed eyewear', 'grey-framed eyewear', 'orange-framed eyewear', 'pink-framed eyewear', 'purple-framed eyewear', 'red-framed eyewear', 'sepia-framed eyewear', 'white-framed eyewear', 'yellow-framed eyewear'],
    "gloves": ['elbow gloves', 'single elbow glove', 'fingerless gloves', 'partially fingerless gloves', 'archery shooting glove', 'artist glove', 'yugake', 'single fingerless glove', 'half gloves', 'paw gloves', 'cat paws', 'santa gloves', 'aqua gloves', 'black gloves', 'blue gloves', 'brown gloves', 'green gloves', 'grey gloves', 'orange gloves', 'pink gloves', 'purple gloves', 'red gloves', 'sepia gloves', 'white gloves', 'yellow gloves', 'multicolored gloves', 'fishnet gloves', 'lace gloves', 'latex gloves', 'leather gloves', 'metal gloves', 'rubber gloves', 'frilled gloves', 'fur-trimmed gloves', 'lace-trimmed gloves', 'print gloves', 'ribbon-trimmed gloves', 'spiked gloves', 'striped gloves', 'torn gloves', 'adjusting gloves', 'glove biting', 'glove in mouth', 'glove pull', 'holding gloves', 'putting on gloves', 'removing glove', 'uneven gloves', 'gloves removed', 'mismatched gloves', 'no gloves', 'single glove', 'single elbow glove', 'single fingerless glove'],
    "gun": ['sniper rifle', 'assault rifle', 'kalashnikov rifle', 'bullpup', 'beam rifle', 'submachine gun', 'rifle'],
    "hair bun": ['double bun', 'single hair bun', 'cone hair bun', 'doughnut hair bun', 'braided bun', 'single side bun'],
    "hair ornament": ['heart hair ornament', 'x hair ornament', 'food-themed hair ornament', 'hair flower', 'star hair ornament', 'hair bell', 'feather hair ornament'],
    "hairband": ['aqua hairband', 'black hairband', 'blue hairband', 'brown hairband', 'green hairband', 'grey hairband', 'orange hairband', 'pink hairband', 'purple hairband', 'red hairband', 'sepia hairband', 'white hairband', 'yellow hairband'],
    "hakama": ['hakama skirt'],
    "hat": ['sun hat', 'aqua headwear', 'black headwear', 'blue headwear', 'brown headwear', 'green headwear', 'grey headwear', 'orange headwear', 'pink headwear', 'purple headwear', 'red headwear', 'sepia headwear', 'white headwear', 'yellow headwear'],
    "high heels": ['high heel boots'],
    "highleg": ['highleg leotard'],
    "holding weapon": ['holding sword', 'holding gun', 'holding polearm', 'holding bow (weapon)'],
    "holding": ['holding book', 'holding bowl', 'holding card', 'holding cup', 'holding condom', 'holding fishing rod', 'holding flower', 'holding food', 'holding gift', 'holding hammer', 'holding phone', 'holding poke ball', 'holding weapon', 'holding candy cane', 'holding fruit', 'holding lollipop', 'holding pizza', 'holding pumpkin', 'holding bra', 'holding eyewear', 'holding hat', 'holding panties', 'holding shoes', 'holding skirt', 'holding fork', 'holding spoon', 'holding bone', 'holding hair', 'holding hands', "holding another's tail", 'holding own tail', 'holding syringe', 'holding balloon', 'holding staff', 'holding camera', 'holding hands', 'holding sword', 'holding gun', 'holding umbrella', 'holding staff', 'holding clothes', 'holding knife', 'holding bag', 'holding bottle', 'holding fan', 'holding tray', 'holding polearm', 'holding microphone', 'holding gift', "holding another's wrist", 'holding instrument', 'holding stuffed toy', 'holding plate', 'holding bouquet', 'holding chopsticks', 'holding wand', 'holding can', 'holding ball', 'holding strap', 'holding cigarette', 'holding candy', 'holding paper', 'holding pen', 'holding shield', 'holding towel', 'holding mask', 'holding box', "holding another's arm", 'holding underwear', 'holding animal'],
    "hood": ['hood down', 'hood up'],
    "hoodie": ['oppai hoodie', 'cropped hoodie', 'polka dot hoodie', 'print hoodie', 'sleeveless hoodie', 'striped hoodie', 'jacket over hoodie', 'hoodie lift', 'hoodie removed', 'naked hoodie', 'open hoodie', 'aqua hoodie', 'black hoodie', 'blue hoodie', 'brown hoodie', 'green hoodie', 'grey hoodie', 'orange hoodie', 'pink hoodie', 'purple hoodie', 'red hoodie', 'sepia hoodie', 'white hoodie', 'yellow hoodie'],
    "horns": ['aqua horns', 'black horns', 'blue horns', 'brown horns', 'green horns', 'grey horns', 'orange horns', 'pink horns', 'purple horns', 'red horns', 'sepia horns', 'white horns', 'yellow horns', 'demon horns', 'dragon horns', 'oni horns', 'cow horns', 'goat horns', 'sheep horns'],
    "instrument": ['playing instrument'],
    "jacket": ['aqua jacket', 'black jacket', 'blue jacket', 'brown jacket', 'green jacket', 'grey jacket', 'orange jacket', 'pink jacket', 'purple jacket', 'red jacket', 'sepia jacket', 'white jacket', 'yellow jacket', 'bomber jacket', 'cropped jacket', 'hooded jacket', 'leather jacket', 'letterman jacket', 'track jacket', 'safari jacket', 'suit jacket', 'jacket on shoulders', 'jacket over shoulder', 'jacket over hoodie', 'open jacket'],
    "joints": ['robot joints'],
    "lantern": ['paper lantern', "jack-o'-lantern", 'stone lantern'],
    "leotard": ['aqua leotard', 'black leotard', 'blue leotard', 'brown leotard', 'green leotard', 'grey leotard', 'orange leotard', 'pink leotard', 'purple leotard', 'red leotard', 'sepia leotard', 'white leotard', 'yellow leotard', 'highleg leotard'],
    "lollipop": ['holding lollipop'],
    "long hair": ['very long hair'],
    "long sleeves": ['puffy long sleeves'],
    "military": ['military uniform', 'military hat'],
    "mole": ['mole under eye', 'mole under mouth', 'mole on breast', 'mole on thigh'],
    "nail polish": ['aqua nails', 'black nails', 'blue nails', 'brown nails', 'green nails', 'grey nails', 'orange nails', 'pink nails', 'purple nails', 'red nails', 'sepia nails', 'white nails', 'yellow nails'],
    "neckerchief": ['aqua neckerchief', 'black neckerchief', 'blue neckerchief', 'brown neckerchief', 'green neckerchief', 'grey neckerchief', 'orange neckerchief', 'pink neckerchief', 'purple neckerchief', 'red neckerchief', 'sepia neckerchief', 'white neckerchief', 'yellow neckerchief'],
    "necklace": ['cross necklace', 'heart necklace', 'bead necklace', 'pearl necklace', 'chain necklace', 'magatama necklace', 'star necklace'],
    "necktie": ['short necktie', 'aqua necktie', 'black necktie', 'blue necktie', 'brown necktie', 'green necktie', 'grey necktie', 'orange necktie', 'pink necktie', 'purple necktie', 'red necktie', 'sepia necktie', 'white necktie', 'yellow necktie'],
    "nude": ['completely nude'],
    "o-ring": ['o-ring top', 'o-ring bikini', 'o-ring bottom', 'o-ring chorker', 'o-ring thigh strap', 'heart o-ring'],
    "on desk": ['sitting on desk'],
    "one-piece swimsuit": ['aqua one-piece swimsuit', 'black one-piece swimsuit', 'blue one-piece swimsuit', 'brown one-piece swimsuit', 'green one-piece swimsuit', 'grey one-piece swimsuit', 'orange one-piece swimsuit', 'pink one-piece swimsuit', 'purple one-piece swimsuit', 'red one-piece swimsuit', 'sepia one-piece swimsuit', 'white one-piece swimsuit', 'yellow one-piece swimsuit', 'casual one-piece swimsuit'],
    "open clothes": ['open jacket', 'open shirt', 'open coat', 'open hoodie', 'open vest', 'open cardigan', 'open kimono', 'open dress'],
    "oral": ['blowjob'],
    "panties": ['aqua panties', 'black panties', 'blue panties', 'brown panties', 'green panties', 'grey panties', 'orange panties', 'pink panties', 'purple panties', 'red panties', 'sepia panties', 'white panties', 'yellow panties'],
    "pants": ['aqua pants', 'black pants', 'blue pants', 'brown pants', 'green pants', 'grey pants', 'orange pants', 'pink pants', 'purple pants', 'red pants', 'sepia pants', 'white pants', 'yellow pants', 'plaid pants', 'pinstripe pants', 'capri pants', 'harem pants', 'leather pants', 'pant suit', 'detached pants', 'lowleg pants', 'no pants', 'pants rolled up', 'tight pants', 'single pantsleg', 'pants pull', 'open pants'],
    "pantyhose": ['aqua pantyhose', 'black pantyhose', 'blue pantyhose', 'brown pantyhose', 'green pantyhose', 'grey pantyhose', 'orange pantyhose', 'pink pantyhose', 'purple pantyhose', 'red pantyhose', 'sepia pantyhose', 'white pantyhose', 'yellow pantyhose'],
    "phone": ['cellphone', 'smartphone', 'corded phone'],
    "piercing": ['ear piercing'],
    "plaid": ['plaid skirt', 'plaid vest', 'plaid shirt', 'plaid scarf', 'plaid bow', 'plaid dress', 'plaid bikini', 'plaid necktie', 'plaid bowtie', 'plaid background', 'plaid headwear', 'plaid pants', 'plaid panties', 'plaid jacket'],
    "pubic hair": ['female pubic hair', 'male pubic hair'],
    "puffy sleeves": ['puffy long sleeves', 'puffy short sleeves'],
    "pussy": ['spread pussy'],
    "racket": ['tennis racket'],
    "ribbon": ['arm ribbon', 'hair ribbon', 'hat ribbon', 'naked ribbon', 'ribbon bondage', 'ribbon choker', 'ribbon hair', 'tail ribbon', 'award ribbon', 'neck ribbon', 'aqua ribbon', 'black ribbon', 'blue ribbon', 'brown ribbon', 'green ribbon', 'grey ribbon', 'orange ribbon', 'pink ribbon', 'purple ribbon', 'red ribbon', 'sepia ribbon', 'white ribbon', 'yellow ribbon'],
    "rifle": ['sniper rifle', 'assault rifle', 'kalashnikov rifle', 'bullpup', 'beam rifle'],
    "scarf": ['aqua scarf', 'black scarf', 'blue scarf', 'brown scarf', 'green scarf', 'grey scarf', 'orange scarf', 'pink scarf', 'purple scarf', 'red scarf', 'sepia scarf', 'white scarf', 'yellow scarf'],
    "see-through": ['see-through shirt', 'see-through sleeves', 'see-through silhouette', 'see-through skirt', 'see-through dress', 'see-through legwear', 'see-through leotard', 'see-through cleavage'],
    "semi-rimless eyewear": ['over-rim eyewear', 'under-rim eyewear'],
    "sex": ['sex from behind', 'standing sex'],
    "shirt": ['aqua shirt', 'black shirt', 'blue shirt', 'brown shirt', 'green shirt', 'grey shirt', 'orange shirt', 'pink shirt', 'purple shirt', 'red shirt', 'sepia shirt', 'white shirt', 'yellow shirt', 'sleeveless shirt', 'shirt lift', 'striped shirt'],
    "shoes": ['high heels', 'aqua footwear', 'black footwear', 'blue footwear', 'brown footwear', 'green footwear', 'grey footwear', 'orange footwear', 'pink footwear', 'purple footwear', 'red footwear', 'sepia footwear', 'white footwear', 'yellow footwear', 'loafers'],
    "short sleeves": ['puffy short sleeves'],
    "shorts": ['aqua shorts', 'black shorts', 'blue shorts', 'brown shorts', 'green shorts', 'grey shorts', 'orange shorts', 'pink shorts', 'purple shorts', 'red shorts', 'sepia shorts', 'white shorts', 'yellow shorts', 'Bike shorts', 'Denim shorts', 'Dolphin shorts', 'Micro shorts', 'Open shorts', 'Short shorts', 'Shorts pull', 'Shorts aside', 'Shorts around one leg'],
    "skirt": ['skirt lift', 'pleated skirt', 'plaid skirt', 'skirt hold', 'aqua skirt', 'black skirt', 'blue skirt', 'brown skirt', 'green skirt', 'grey skirt', 'orange skirt', 'pink skirt', 'purple skirt', 'red skirt', 'sepia skirt', 'white skirt', 'yellow skirt'],
    "sky": ['blue sky', 'cloudy sky', 'clear sky', 'night sky', 'starry sky'],
    "sleeveless": ['sleeveless shirt', 'sleeveless dress', 'sleeveless turtleneck', 'sleeveless jacket', 'sleeveless sweater', 'sleeveless kimono', 'sleeveless hoodie'],
    "socks": ['aqua socks', 'black socks', 'blue socks', 'brown socks', 'green socks', 'grey socks', 'orange socks', 'pink socks', 'purple socks', 'red socks', 'sepia socks', 'white socks', 'yellow socks'],
    "sportswear": ['baseball uniform', 'american football uniform', 'basketball uniform', 'rugby uniform', 'soccer uniform', 'softball uniform', 'tennis uniform'],
    "spread legs": ['v-shaped spread legs'],
    "squatting": ['squatting cowgirl position'],
    "standing": ['standing doggy', 'standing sex'],
    "strapless": ['strapless dress', 'strapless bikini', 'strapless leotard', 'strapless shirt', 'strapless bra', 'strapless swimsuit'],
    "suspenders": ['suspender skirt', 'suspender shorts'],
    "sweater": ['aqua sweater', 'black sweater', 'blue sweater', 'brown sweater', 'green sweater', 'grey sweater', 'orange sweater', 'pink sweater', 'purple sweater', 'red sweater', 'sepia sweater', 'white sweater', 'yellow sweater'],
    "swimsuit": ['bikini', 'school swimsuit', 'competition swimsuit', 'one-piece swimsuit', 'strapless swimsuit'],
    "tail": ['fish tail', 'shark tail', 'demon tail', 'rabbit tail', 'mouse tail', 'fox tail', 'dog tail', 'cat tail', 'horse tail', 'wolf tail', 'dragon tail', 'raccoon tail'],
    "teeth": ['sharp teeth'],
    "thighhighs": ['aqua thighhighs', 'black thighhighs', 'blue thighhighs', 'brown thighhighs', 'green thighhighs', 'grey thighhighs', 'orange thighhighs', 'pink thighhighs', 'purple thighhighs', 'red thighhighs', 'sepia thighhighs', 'white thighhighs', 'yellow thighhighs'],
    "thighs": ['ass visible through thighs', 'thighhighs', 'thigh strap'],
    "toenails": ['toenail polish'],
    "tongue": ['tongue out'],
    "transparent": ['transparent umbrella'],
    "tree": ['palm tree', 'christmas tree', 'against tree'],
    "twintails": ['low twintails'],
    "weapon": ['cleaning weapon', 'holding weapon', 'licking weapon', 'pointing weapon', 'weapon in garters', 'weapon behind back', 'weapon on back', 'weapon over shoulder', 'alternate weapon', 'blood on weapon', 'broken weapon', 'glowing weapon', 'huge weapon', 'weapon connection', 'weapon request', 'sword', 'gun', 'katana', 'spear', 'bow (weapon)'],
    "wings": ['aqua wings', 'black wings', 'blue wings', 'brown wings', 'green wings', 'grey wings', 'orange wings', 'pink wings', 'purple wings', 'red wings', 'sepia wings', 'white wings', 'yellow wings', 'fairy wings', 'demon wings', 'angel wings', 'dragon wings', 'butterfly wings'],
    "sailor collar": ['aqua sailor collar', 'black sailor collar', 'blue sailor collar', 'brown sailor collar', 'green sailor collar', 'grey sailor collar', 'orange sailor collar', 'pink sailor collar', 'purple sailor collar', 'red sailor collar', 'sepia sailor collar', 'white sailor collar', 'yellow sailor collar'],
    "crop top": ['crop top overhang'],
    "crown": ['mini crown'],
    "bra": ['aqua bra', 'black bra', 'blue bra', 'brown bra', 'green bra', 'grey bra', 'orange bra', 'pink bra', 'purple bra', 'red bra', 'sepia bra', 'white bra', 'yellow bra'],
    "headwear removed": ['hat removed'],
    "headphones": ['headphones around neck'],
    "ground vehicle": ['motor vehicle', 'motorcycle'],
    "motor vehicle": ['motorcycle'],
    "helmet": ['motorcycle helmet'],
    "tank top": ['aqua tank top', 'black tank top', 'blue tank top', 'brown tank top', 'green tank top', 'grey tank top', 'orange tank top', 'pink tank top', 'purple tank top', 'red tank top', 'sepia tank top', 'white tank top', 'yellow tank top'],
    "lips": ['parted lips'],
    "stuffed toy": ['holding stuffed toy', 'stuffed animal'],
    "stuffed animal": ['teddy bear'],
    "butterfly": ['aqua butterfly', 'black butterfly', 'blue butterfly', 'brown butterfly', 'green butterfly', 'grey butterfly', 'orange butterfly', 'pink butterfly', 'purple butterfly', 'red butterfly', 'sepia butterfly', 'white butterfly', 'yellow butterfly'],
    "animal": ['butterfly', 'cat', 'dog', 'bird'],
    "snow": ['snowing'],
    "cross": ['cross necklace', 'latin cross'],
    "rose": ['aqua rose', 'black rose', 'blue rose', 'brown rose', 'green rose', 'grey rose', 'orange rose', 'pink rose', 'purple rose', 'red rose', 'sepia rose', 'white rose', 'yellow rose'],
    "gem": ['aqua gemstone', 'black gemstone', 'blue gemstone', 'brown gemstone', 'green gemstone', 'grey gemstone', 'orange gemstone', 'pink gemstone', 'purple gemstone', 'red gemstone', 'sepia gemstone', 'white gemstone', 'yellow gemstone'],
    "vest": ['aqua vest', 'black vest', 'blue vest', 'brown vest', 'green vest', 'grey vest', 'orange vest', 'pink vest', 'purple vest', 'red vest', 'sepia vest', 'white vest', 'yellow vest'],
    "hug": ['animal hug'],
    "cup": ['teacup'],
    "between legs": ['hand between legs'],
    "leather": ['leather jacket', 'leather gloves', 'leather boots', 'leather belt'],
}
